# Generated by Django 2.2.3 on 2019-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
